<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_admin_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_admin_user by adminId
     */
    function get_gb_admin_user($adminId)
    {
        return $this->db->get_where('gb_admin_users',array('adminId'=>$adminId))->row_array();
    }
        
    /*
     * Get all gb_admin_users
     */
    function get_all_gb_admin_users()
    {
        $this->db->order_by('adminId', 'desc');
        return $this->db->get('gb_admin_users')->result_array();
    }
        
    /*
     * function to add new gb_admin_user
     */
    function add_gb_admin_user($params)
    {
        $this->db->insert('gb_admin_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_admin_user
     */
    function update_gb_admin_user($adminId,$params)
    {
        $this->db->where('adminId',$adminId);
        return $this->db->update('gb_admin_users',$params);
    }
    
    /*
     * function to delete gb_admin_user
     */
    function delete_gb_admin_user($adminId)
    {
        return $this->db->delete('gb_admin_users',array('adminId'=>$adminId));
    }
}
