<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_control_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_control by entryId
     */
    function get_gb_control($entryId)
    {
        return $this->db->get_where('gb_control',array('entryId'=>$entryId))->row_array();
    }
        
    /*
     * Get all gb_control
     */
    function get_all_gb_control()
    {
        $this->db->order_by('entryId', 'desc');
        return $this->db->get('gb_control')->result_array();
    }
        
    /*
     * function to add new gb_control
     */
    function add_gb_control($params)
    {
        $this->db->insert('gb_control',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_control
     */
    function update_gb_control($entryId,$params)
    {
        $this->db->where('entryId',$entryId);
        return $this->db->update('gb_control',$params);
    }

    /**
     * function to get studentid for new student entry
     * @return string <unique studentId >
     */
    function get_gb_studentId()
    {
        $this->db->order_by('entryId', 'desc');
        //control file is designed to have one row
        //if there are many grabe the last row inserted as a safety measure
        $control =  $this->db->get('gb_control')->first_row('array');
        $student_id = $control['currentTerm'] . $control['studentHeader'];
        $new_header =  (int) ($control['studentHeader'] + 1);
        $prams = array(
            'studentHeader' => $new_header
        );
        return($this->update_gb_control($control['entryId'], $prams) == true ? $student_id : 0 );
    }
    
    /*
     * function to delete gb_control
     */
    function delete_gb_control($entryId)
    {
        return $this->db->delete('gb_control',array('entryId'=>$entryId));
    }
}
