<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_classe_list_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_classe_list by studentId
     */
    function get_gb_classe_list($studentId)
    {
        return $this->db->get_where('gb_classe_list',array('studentId'=>$studentId))->row_array();
    }
        
    /*
     * Get all gb_classe_list
     */
    function get_all_gb_classe_list()
    {
        $this->db->order_by('studentId', 'desc');
        return $this->db->get('gb_classe_list')->result_array();
    }
        
    /*
     * function to add new gb_classe_list
     */
    function add_gb_classe_list($params)
    {
        $this->db->insert('gb_classe_list',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_classe_list
     */
    function update_gb_classe_list($studentId,$params)
    {
        $this->db->where('studentId',$studentId);
        return $this->db->update('gb_classe_list',$params);
    }
    
    /*
     * function to delete gb_classe_list
     */
    function delete_gb_classe_list($studentId)
    {
        return $this->db->delete('gb_classe_list',array('studentId'=>$studentId));
    }
}
