<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_gurdian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_gurdian by gurdianId
     */
    function get_gb_gurdian($gurdianId)
    {
        return $this->db->get_where('gb_gurdians',array('gurdianId'=>$gurdianId))->row_array();
    }

    
    /*
     * Get gb_gurdian by studentld
     */
    function get_gb_student_gurdian($studentId)
    {
        return $this->db->get_where('gb_gurdians',array('studentId'=>$studentId))->result_array();
    }
        
    /*
     * Get all gb_gurdians
     */
    function get_all_gb_gurdians()
    {
        $this->db->order_by('gurdianId', 'desc');
        return $this->db->get('gb_gurdians')->result_array();
    }
        
    /*
     * function to add new gb_gurdian
     */
    function add_gb_gurdian($params)
    {
        $this->db->insert('gb_gurdians',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_gurdian
     */
    function update_gb_gurdian($gurdianId,$params)
    {
        $this->db->where('gurdianId',$gurdianId);
        return $this->db->update('gb_gurdians',$params);
    }
    
    /*
     * function to delete gb_gurdian
     */
    function delete_gb_gurdian($gurdianId)
    {
        return $this->db->delete('gb_gurdians',array('gurdianId'=>$gurdianId));
    }
}
