<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_grade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_grade by gradeId
     */
    function get_gb_grade($gradeId)
    {
        return $this->db->get_where('gb_grades',array('gradeId'=>$gradeId))->row_array();
    }
        
    /*
     * Get all gb_grades
     */
    function get_all_gb_grades()
    {
        $this->db->order_by('gradeId', 'desc');
        return $this->db->get('gb_grades')->result_array();
    }
        
    /*
     * function to add new gb_grade
     */
    function add_gb_grade($params)
    {
        $this->db->insert('gb_grades',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_grade
     */
    function update_gb_grade($gradeId,$params)
    {
        $this->db->where('gradeId',$gradeId);
        return $this->db->update('gb_grades',$params);
    }
    
    /*
     * function to delete gb_grade
     */
    function delete_gb_grade($gradeId)
    {
        return $this->db->delete('gb_grades',array('gradeId'=>$gradeId));
    }
}
