<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_message_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_message by messageId
     */
    function get_gb_message($messageId)
    {
        return $this->db->get_where('gb_messages',array('messageId'=>$messageId))->row_array();
    }
        
    /*
     * Get all gb_messages
     */
    function get_all_gb_messages()
    {
        $this->db->order_by('messageId', 'desc');
        return $this->db->get('gb_messages')->result_array();
    }
        
    /*
     * function to add new gb_message
     */
    function add_gb_message($params)
    {
        $this->db->insert('gb_messages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_message
     */
    function update_gb_message($messageId,$params)
    {
        $this->db->where('messageId',$messageId);
        return $this->db->update('gb_messages',$params);
    }
    
    /*
     * function to delete gb_message
     */
    function delete_gb_message($messageId)
    {
        return $this->db->delete('gb_messages',array('messageId'=>$messageId));
    }
}
