<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_syllabus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_syllabus by syllabusId
     */
    function get_gb_syllabus($syllabusId)
    {
        return $this->db->get_where('gb_syllabuses',array('syllabusId'=>$syllabusId))->row_array();
    }
        
    /*
     * Get all gb_syllabuses
     */
    function get_all_gb_syllabuses()
    {
        $this->db->order_by('syllabusId', 'desc');
        return $this->db->get('gb_syllabuses')->result_array();
    }
        
    /*
     * function to add new gb_syllabus
     */
    function add_gb_syllabus($params)
    {
        $this->db->insert('gb_syllabuses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_syllabus
     */
    function update_gb_syllabus($syllabusId,$params)
    {
        $this->db->where('syllabusId',$syllabusId);
        return $this->db->update('gb_syllabuses',$params);
    }
    
    /*
     * function to delete gb_syllabus
     */
    function delete_gb_syllabus($syllabusId)
    {
        return $this->db->delete('gb_syllabuses',array('syllabusId'=>$syllabusId));
    }
}
