<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_student by studentId
     */
    function get_gb_student($studentId)
    {
        return $this->db->get_where('gb_students',array('studentId'=>$studentId))->row_array();
    }
    /*
     * checks if a matching student is in the database
     * @return boolean if match is found   
     */
    function check_gb_student_exist($f_name, $l_name, $sex, $dob)
    {
        $where_array = array(
                        'firstName'=>$f_name,
                        'lastName' => $l_name,
                        'sex' => $sex,
                        'dateOfBirth' => $dob
                       );
        $this->db->where($where_array);
        $this->db->from('gb_students');
        return ( $this->db->count_all_results() > 0 ? true : false);
    }
      
    /*
     * Get all gb_students
     */
    function get_all_gb_students()
    {
        $this->db->order_by('studentId', 'desc');
        return $this->db->get('gb_students')->result_array();
    }
        
    /*
     * function to add new gb_student
     */
    function add_gb_student($params)
    {
        return  $this->db->insert('gb_students',$params);
    }
    
    /*
     * function to update gb_student
     */
    function update_gb_student($studentId,$params)
    {
        $this->db->where('studentId',$studentId);
        return $this->db->update('gb_students',$params);
    }
    
    /*
     * function to delete gb_student
     */
    function delete_gb_student($studentId)
    {
        return $this->db->delete('gb_students',array('studentId'=>$studentId));
    }
}
