<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_teacher_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_teacher by teacherId
     */
    function get_gb_teacher($teacherId)
    {
        return $this->db->get_where('gb_teachers',array('teacherId'=>$teacherId))->row_array();
    }
        
    /*
     * Get all gb_teachers
     */
    function get_all_gb_teachers()
    {
        $this->db->order_by('teacherId', 'desc');
        return $this->db->get('gb_teachers')->result_array();
    }
        
    /*
     * function to add new gb_teacher
     */
    function add_gb_teacher($params)
    {
        $this->db->insert('gb_teachers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_teacher
     */
    function update_gb_teacher($teacherId,$params)
    {
        $this->db->where('teacherId',$teacherId);
        return $this->db->update('gb_teachers',$params);
    }
    
    /*
     * function to delete gb_teacher
     */
    function delete_gb_teacher($teacherId)
    {
        return $this->db->delete('gb_teachers',array('teacherId'=>$teacherId));
    }
}
