<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_user by userId
     */
    function get_gb_user($userId)
    {
        return $this->db->get_where('gb_users',array('userId'=>$userId))->row_array();
    }
     
    /*
     * Get gb_user by userId
     */
    function get_gb_user_by_username($userName)
    {
        return $this->db->get_where('gb_users',array('userName'=>$userName))->row_array();
    }
    /*
     * Get all gb_users
     */
    function get_all_gb_users()
    {
        $this->db->order_by('userId', 'desc');
        return $this->db->get('gb_users')->result_array();
    }
        
    /*
     * function to add new gb_user
     */
    function add_gb_user($params)
    {
        $this->db->insert('gb_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_user
     */
    function update_gb_user($userId,$params)
    {
        $this->db->where('userId',$userId);
        return $this->db->update('gb_users',$params);
    }
    
    /*
     * function to delete gb_user
     */
    function delete_gb_user($userId)
    {
        return $this->db->delete('gb_users',array('userId'=>$userId));
    }
}
