<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_exam_paper_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_exam_paper by paperId
     */
    function get_gb_exam_paper($paperId)
    {
        return $this->db->get_where('gb_exam_papers',array('paperId'=>$paperId))->row_array();
    }
        
    /*
     * Get all gb_exam_papers
     */
    function get_all_gb_exam_papers()
    {
        $this->db->order_by('paperId', 'desc');
        return $this->db->get('gb_exam_papers')->result_array();
    }
        
    /*
     * function to add new gb_exam_paper
     */
    function add_gb_exam_paper($params)
    {
        $this->db->insert('gb_exam_papers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_exam_paper
     */
    function update_gb_exam_paper($paperId,$params)
    {
        $this->db->where('paperId',$paperId);
        return $this->db->update('gb_exam_papers',$params);
    }
    
    /*
     * function to delete gb_exam_paper
     */
    function delete_gb_exam_paper($paperId)
    {
        return $this->db->delete('gb_exam_papers',array('paperId'=>$paperId));
    }
}
