<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gb_insititute_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gb_insititute by 
     */
    function get_gb_insititute($)
    {
        return $this->db->get_where('gb_insititute',array(''=>$))->row_array();
    }
        
    /*
     * Get all gb_insititute
     */
    function get_all_gb_insititute()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('gb_insititute')->result_array();
    }
        
    /*
     * function to add new gb_insititute
     */
    function add_gb_insititute($params)
    {
        $this->db->insert('gb_insititute',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gb_insititute
     */
    function update_gb_insititute($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('gb_insititute',$params);
    }
    
    /*
     * function to delete gb_insititute
     */
    function delete_gb_insititute($)
    {
        return $this->db->delete('gb_insititute',array(''=>$));
    }
}
